kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: rancher-deploy
  image: peloton/drone-rancher
  envorontment:
    RANCHER_URL:
      from_secret: url
    RANCHER_ACCESS_KEY:
      from_secret: access_key
    RANCHER_SECRET_KEY:
      from_secret: secret_key
  settings:
    service: web/basic-node
    docker_image: dascencio/basic-node
    start_first: true
    confirm: true
    timeout: 180