kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: deploy
  image: dascencio/kubectl:1.0.0
  secrets: [ KUBE_CONFIG ]
  environment:
    K8S_CONFIG:
      from_secret: KUBE_CONFIG
  commands:
  - mkdir -p ~/.kube
  - echo $K8S_CONFIG | base64 -d > ~/.kube/config
  - kubectl -n Default get pods