kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: deploy
  image: dascencio/kubectl:1.0.0
<<<<<<< HEAD
  secrets: [ KUBE_CONFIG ]
  commands:
  - mkdir -p ~/.kube
  - echo $KUBECONFIG | base64 -d > ~/.kube/config
=======
  environment:
    KUBE_CONFIG:
      from_secret: KUBE_CONFIG
  secrets: [ KUBE_CONFIG ]
  commands:
  - mkdir -p ~/.kube
  - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
>>>>>>> 154b983d701ae45d14486ae52fe52b964cde8f29
  - kubectl get nodes