kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: registry  
  image: plugins/docker
  secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
  environment:
    USERNAME:
      from_secret: DOCKER_USERNAME
    PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - export DOCKER_USER=$(echo $USERNAME | base64 -d);
  - export DOCKER_PASS=$(echo $PASSWORD | base64 -d);
  settings:
    username: $DOCKER_USER
    password: $DOCKER_PASS
    repo: $DOCKER_USER/basic-node
    dockerfile: Dockerfile
    tags: 
      - 1.0.1
      - latest

#- name: deploy
#  image: dascencio/kubectl:1.0.0
#  secrets: [ KUBE_CONFIG ]
#  environment:
#    K8S_CONFIG:
#      from_secret: KUBE_CONFIG
#  commands:
#  - mkdir -p ~/.kube
#  - echo $K8S_CONFIG | base64 -d > ~/.kube/config
#  - kubectl get pods