kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: rancher-deploy
  image: peloton/drone-rancher
  settings:
    url:
      from_secret: RANCHER_URL
    access_key:
      from_secret: RANCHER_ACCESS_KEY
    secret_key:
      from_secret: RANCHER_SECRET_KEY
    service: web/basic-node
    docker_image: dascencio/basic-node
    start_first: true
    confirm: true
    timeout: 180
    