kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: deploy
  image: bitnami/kubectl
  commands:
  - echo $KUBE_CONFIG | base64 -d > .kube/config
  - kubectl get nodes