kind: pipeline
name: basic-node

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm install

- name: deploy
  image: dascencio/kubectl:1.0.0
  environment:
    KUBECONFIG:
      from_secret: KUBE_CONFIG
  secrets: [ KUBE_CONFIG ]
  commands:
  - mkdir -p ~/.kube
  - $KUBECONFIG | base64 -d > ~/.kube/config
  - kubectl get nodes