apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-node-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-node
    spec:
      containers:
      - name: web-node
        image: dascencio/basic-node
        ports:
        - containerPort: 3000